version: '3'

services:
  php:
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: mtgcredit-php
    restart: unless-stopped
    ports:
     - 80:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql
    container_name: mtgcredit-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped 
    environment:
      MYSQL_ROOT_PASSWORD: DEcaLbcqMoGLbfj7
    volumes:
     - ./mysql:/var/lib/mysql
     - ./mysql-app:/app
    ports:
      - 3306:3306
    working_dir: /app

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped 
    ports:
      - 8080:8080
